<%@ Page Language="C#" MasterPageFile="~/Web.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs"
    Inherits="AssessmentManager.Default" Title="Survey Manager" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <h1 class="PageTitle">
        Survey Manager</h1>
    <asp:Panel Style="text-align: center" Width="99%" ID="panSurvey" runat="server" Visible="true"
        BorderColor="SteelBlue" BorderStyle="Solid" BorderWidth="1">
        <h2 class="SectionTitle">
            Survey</h2>
        <asp:GridView ID="gridSurvey" runat="server" AutoGenerateColumns="False" CssClass="GridMain"
            AutoGenerateEditButton="True" OnRowEditing="gridSurvey_OnRowEditing" AutoGenerateDeleteButton="True"
            OnRowDeleting="gridSurvey_OnRowDeleting" AutoGenerateSelectButton="True" OnSelectedIndexChanging="gridSurvey_OnRowSelecting"
            OnRowUpdating="gridSurvey_RowUpdating" OnRowCancelingEdit="gridSurvey_RowCancelingEdit">
            <RowStyle CssClass="GridRow" />
            <SelectedRowStyle CssClass="GridSelectedRow" />
            <HeaderStyle CssClass="GridHeader" />
            <EmptyDataRowStyle CssClass="GridEmptyRow" />
            <EmptyDataTemplate>
                No data found.
            </EmptyDataTemplate>
            <Columns>
                <asp:BoundField DataField="Survey Id" HeaderText="Survey Id" ReadOnly="true" />
                <asp:BoundField DataField="Survey Title" HeaderText="Survey Title" />
            </Columns>
        </asp:GridView>
        <br />
        <p style="text-align: right;">
            <asp:Button ID="btnAddSurvey" runat="server" OnClick="btnAddSurvey_Click" Text="New Survey"
                Width="150px" />&nbsp;
            <asp:Button ID="btnCloseSurvey" runat="server" OnClick="btnCloseSurvey_Click" Text="Close"
                Width="150px" />&nbsp;
        </p>
        <p style="text-align: left;">
            <asp:Label ID="lblAddSurvey" runat="server" Text="Enter New Survey Title:" Visible="false"></asp:Label>
            <asp:TextBox ID="txtAddSurvey" runat="server" Visible="false"></asp:TextBox>
            <asp:Button ID="btnAddSurveyOk" runat="server" Text="OK" Visible="false" OnClick="btnAddSurveyOk_Click" />
            <asp:Button ID="btnAddSurveyCancel" runat="server" Text="Cancel" Visible="false"
                OnClick="btnAddSurveyCancel_Click" />
        </p>
    </asp:Panel>
    <asp:Panel Style="text-align: center; vertical-align: top;" Width="99%" ID="panSection"
        runat="server" Visible="false" BorderColor="SteelBlue" BorderStyle="Solid" BorderWidth="1">
        <h2 class="SectionTitle">
            Section</h2>
        <asp:Label ID="lblSectionTitle" runat="server" CssClass="SectionSubtitle" Text="Sections For Survey: {0}"></asp:Label><br />
        <asp:GridView ID="gridSection" runat="server" AutoGenerateColumns="false" CssClass="GridMain"
            AutoGenerateEditButton="True" OnRowEditing="gridSection_OnRowEditing" AutoGenerateDeleteButton="True"
            OnRowDeleting="gridSection_OnRowDeleting" AutoGenerateSelectButton="True" OnSelectedIndexChanging="gridSection_OnRowSelecting"
            OnRowCancelingEdit="gridSection_RowCancelingEdit" OnRowUpdating="gridSection_RowUpdating">
            <RowStyle CssClass="GridRow" />
            <SelectedRowStyle CssClass="GridSelectedRow" />
            <HeaderStyle CssClass="GridHeader" />
            <EmptyDataRowStyle CssClass="GridEmptyRow" />
            <EmptyDataTemplate>
                No data found.
            </EmptyDataTemplate>
            <Columns>
                <asp:BoundField DataField="SectionId" HeaderText="Section Id" ReadOnly="true" />
                <asp:BoundField DataField="SectionTitle" HeaderText="Section Title" />
            </Columns>
        </asp:GridView>
        <br />
        <p style="text-align: right;">
            <asp:Button ID="btnAddSection" runat="server" Width="150px" OnClick="btnAddSection_Click"
                Text="New Section" />
            &nbsp;
            <asp:Button ID="btnCloseSection" runat="server" Width="150px" OnClick="btnCloseSection_Click"
                Text="Back" />&nbsp;
        </p>
        <p style="text-align: left;">
            <asp:Label ID="lblAddSection" runat="server" Text="Enter New Section Title:" Visible="false"></asp:Label>
            <asp:TextBox ID="txtAddSection" runat="server" Visible="false"></asp:TextBox>
            <asp:Button ID="btnAddSectionOk" runat="server" Text="OK" Visible="false" OnClick="btnAddSectionOk_Click" />
            <asp:Button ID="btnAddSectionCancel" runat="server" Text="Cancel" Visible="false"
                OnClick="btnAddSectionCancel_Click" />
        </p>
    </asp:Panel>
    <asp:Panel Style="text-align: center; vertical-align: top;" Width="99%" ID="panSubsection"
        runat="server" Visible="false" BorderColor="SteelBlue" BorderStyle="Solid" BorderWidth="1">
        <h2 class="SectionTitle">
            Subsection</h2>
        <asp:Label ID="lblSubsectionTitle" runat="server" CssClass="SectionSubtitle" Text="Subsections For Section: {0}"></asp:Label><br />
        <asp:GridView ID="gridSubsection" runat="server" AutoGenerateColumns="false" CssClass="GridMain"
            AutoGenerateEditButton="True" OnRowEditing="gridSubsection_OnRowEditing" AutoGenerateDeleteButton="True"
            OnRowDeleting="gridSubsection_OnRowDeleting" AutoGenerateSelectButton="True"
            OnSelectedIndexChanging="gridSubsection_OnRowSelecting" OnRowCancelingEdit="gridSubsection_RowCancelingEdit"
            OnRowUpdating="gridSubsection_RowUpdating">
            <RowStyle CssClass="GridRow" />
            <SelectedRowStyle CssClass="GridSelectedRow" />
            <HeaderStyle CssClass="GridHeader" />
            <EmptyDataRowStyle CssClass="GridEmptyRow" />
            <EmptyDataTemplate>
                No data found.
            </EmptyDataTemplate>
            <Columns>
                <asp:BoundField DataField="SubsectionId" HeaderText="Subsection Id" ReadOnly="true" />
                <asp:BoundField DataField="SubsectionTitle" HeaderText="Subsection Title" />
            </Columns>
        </asp:GridView>
        <br />
        <p style="text-align: right;">
            <asp:Button ID="btnAddSubsection" runat="server" OnClick="btnAddSubsection_Click"
                Text="New Subsection" Width="150px" />
            &nbsp;
            <asp:Button ID="btnCloseSubsection" runat="server" OnClick="btnCloseSubsection_Click"
                Text="Back" Width="150px" />&nbsp;
        </p>
        <p style="text-align: left;">
            <asp:Label ID="lblAddSubsection" runat="server" Text="Enter New Subsection Title:"
                Visible="false"></asp:Label>
            <asp:TextBox ID="txtAddSubsection" runat="server" Visible="false"></asp:TextBox>
            <asp:Button ID="btnAddSubsectionOk" runat="server" Text="OK" Visible="false" OnClick="btnAddSubsectionOk_Click" />
            <asp:Button ID="btnAddSubsectionCancel" runat="server" Text="Cancel" Visible="false"
                OnClick="btnAddSubsectionCancel_Click" />
        </p>
    </asp:Panel>
    <asp:Panel Style="text-align: center; vertical-align: top;" Width="99%" ID="panQuestion"
        runat="server" Visible="false" BorderColor="SteelBlue" BorderStyle="Solid" BorderWidth="1">
        <h2 class="SectionTitle">
            Question</h2>
        <asp:Label ID="lblQuestionTitle" runat="server" CssClass="SectionSubtitle" Text="Questions For Subsection: {0}"></asp:Label><br />
        <asp:GridView ID="gridQuestion" runat="server" AutoGenerateColumns="false" CssClass="GridMain"
            AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True"
            OnSelectedIndexChanging="gridQuestion_OnRowSelecting" OnRowEditing="gridQuestion_OnRowEditing"
            OnRowDeleting="gridQuestion_OnRowDeleting" OnRowCancelingEdit="gridQuestion_RowCancelingEdit"
            OnRowUpdating="gridQuestion_RowUpdating">
            <RowStyle CssClass="GridRow" />
            <SelectedRowStyle CssClass="GridSelectedRow" />
            <HeaderStyle CssClass="GridHeader" />
            <EmptyDataRowStyle CssClass="GridEmptyRow" />
            <EmptyDataTemplate>
                No data found.
            </EmptyDataTemplate>
            <Columns>
                <asp:BoundField DataField="QuestionId" HeaderText="Id" ReadOnly="true" />
                <asp:BoundField DataField="Question" HeaderText="Question Text" ReadOnly="false" />
                <asp:BoundField DataField="Order" HeaderText="Order" ReadOnly="false" />
            </Columns>
        </asp:GridView>
        <br />
        <p style="text-align: right;">
            <asp:Button ID="btnAddNewQuestion" runat="server" OnClick="btnAddQuestion_Click"
                Text="Add New Question" Width="150px" />
            &nbsp;
            <asp:Button ID="btnCloseQuestion" runat="server" OnClick="btnCloseQuestion_Click"
                Text="Back" Width="150px" />&nbsp;
        </p>
        <p style="text-align: left;">
            <asp:Label ID="lblAddQuestion" runat="server" Text="Enter New Question:" Visible="false"></asp:Label>
            <asp:TextBox ID="txtAddQuestion" runat="server" Visible="false" width="50%"></asp:TextBox>
            <asp:Button ID="btnAddQuestionOk" runat="server" Text="OK" Visible="false" OnClick="btnAddQuestionOk_Click" />
            <asp:Button ID="btnAddQuestionCancel" runat="server" Text="Cancel" Visible="false"
                OnClick="btnAddQuestionCancel_Click" />
        </p>
        <p style="text-align: left;">
            <asp:GridView ID="responsesGrid" runat="server" AutoGenerateColumns="False" OnSelectedIndexChanged="responsesGrid_SelectedIndexChanged">
                <Columns>
                    <asp:TemplateField HeaderText="Add">
                        <ItemTemplate>
                            <asp:CheckBox ID="addCheckBox" runat="server" />
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="ResponseId" HeaderText="ResponseId" />
                    <asp:BoundField DataField="Response" HeaderText="Response" />
                </Columns>
            </asp:GridView>
        </p>
    </asp:Panel>
    <asp:Panel Style="text-align: center; vertical-align: top;" Width="99%" ID="panResponse"
        runat="server" Visible="false" BorderColor="SteelBlue" BorderStyle="Solid" BorderWidth="1">
        <h2 class="SectionTitle">
            Response</h2>
        <asp:Label ID="lblResponseTitle" runat="server" CssClass="SectionSubtitle" Text="Responses For Question: {0}"></asp:Label><br />
        <asp:GridView ID="gridResponse" runat="server" AutoGenerateColumns="false" CssClass="GridMain"
            AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" OnSelectedIndexChanging="gridResponse_OnRowSelecting"
            OnRowEditing="gridResponse_OnRowEditing" OnRowDeleting="gridResponse_OnRowDeleting"
            OnRowCancelingEdit="gridResponse_RowCancelingEdit" OnRowUpdating="gridResponse_RowUpdating">
            <RowStyle CssClass="GridRow" />
            <SelectedRowStyle CssClass="GridSelectedRow" />
            <HeaderStyle CssClass="GridHeader" />
            <EmptyDataRowStyle CssClass="GridEmptyRow" />
            <EmptyDataTemplate>
                No data found.
            </EmptyDataTemplate>
            <Columns>
                <asp:BoundField DataField="ResponseId" HeaderText="Response Id" ReadOnly="true" />
                <asp:BoundField DataField="Response" HeaderText="Response Text" ReadOnly="false" />
            </Columns>
        </asp:GridView>
        <br />
        <p style="text-align: right;">
            <asp:Button ID="btnAddResponse" runat="server" OnClick="btnAddResponse_Click" Text="Add New Response"
                Width="150px" />
            &nbsp;
            <asp:Button ID="btnCloseResponse" runat="server" OnClick="btnCloseResponse_Click"
                Text="Close" Width="150px" />
            &nbsp;
        </p>
        <p style="text-align: left;">
            <asp:Label ID="lblAddResponse" runat="server" Text="Enter New Response:" Visible="false"></asp:Label>
            <asp:TextBox ID="txtAddResponse" runat="server" Visible="false"></asp:TextBox>
            <asp:Button ID="btnAddResponseOk" runat="server" Text="OK" Visible="false" OnClick="btnAddResponseOk_Click" />
            <asp:Button ID="btnAddResponseCancel" runat="server" Text="Cancel" Visible="false"
                OnClick="btnAddResponseCancel_Click" />
        </p>
    </asp:Panel>
    <asp:Label ID="lblStatus" runat="server" ForeColor="Red" Width="98%"></asp:Label>
</asp:Content>
